name: QA react automation 
on:
    schedule:
    - cron: "*/5 * * * *"
    workflow_dispatch:
jobs: 
    automation_running:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Install dependencies
          run: | 
                npm init playwright
                npm install @playwright/test
                npx playwright install 
        - name: Run Playwright tests
          run: npm run todomvc
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
        - uses: actions/upload-artifact@master
          with:
            name: allure-results
            path: allure-results
            retention-days: 20
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages
    
        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20

        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: 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
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history